# Generated by Django 3.1.4 on 2020-12-18 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('title', models.CharField(max_length=256)),
                ('link', models.URLField(max_length=256)),
                ('amount_of_upvotes', models.SmallIntegerField(default=0)),
                ('author_name', models.CharField(default='unknown author', max_length=128)),
            ],
            options={
                'verbose_name_plural': 'News',
                'ordering': ['-amount_of_upvotes', 'create_date'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('comment_author_name', models.CharField(default='unknown user', max_length=128)),
                ('text', models.TextField(max_length=512)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='news_board.news')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
